name: generate readme animation

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *"

  # 允许随时手动运行作业
  workflow_dispatch:

  # run on every push on the master branch
  push:
    branches:
      - main



jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
